### ISSUE TITLE
Lint Issue

### ISSUE THREAD

**Issue by Emmy-github-webdev** [lu-jim/bootstrap-portfolio#2]
## Fix lint error

Great job :clap: :clap: :clap: :clap:

Put on the momentum and correct the lint error.

Thanks. :beer:

**Comment by Medini-Rajendra** [comment]
Great job finishing the bootstrap project. There is nothing else to comment except good job. Keep going!!!

**Comment by lu-jim** [comment]
Fixed the linting error!
